sudo: false
language: python
env:
  matrix:
  - TESTENV=py27
  - TESTENV=py34
  - TESTENV=coveralls
  global:
    secure: e6MspASLp7ziqDQZMwcUhvc4cGv8MRdg90klOQWwvZmos3T3ilvRtbmrqFqoJUwCWKyqAmIc/zZJOCpaJXakMI60VvmNFN/KfGxQDGOtT9E/c2O7iiyYiw8hxjVgdRrERZurkJQJlOF8xQgB8MeLnj9NjGdqL5vxw/lx97jbRzSHVwB844QXZ7Sg2sB6w+M+vytaEg9iC+m6Z3aqlwdKvdu5Or28LsqXRDBTRIU5ClB6KxRladaoaPjeSJCnkgrhrTzb4v0sLwViEiVB0DlXljIgtMNJD8dTdsTlqYeTKc/PkKAGvnZLaJNYjmng1HEqLm3wp/ZlS9J69GqNmkrtBXy1V4FUWTJYR/cMIw/mjd+p8k/B4sBYACl4YOlIDMM+K/trcmzzThEAG3h+2as1ZhGhUH9piu5FL+gqzopSlm709ZbYqK8gG83wljqELN+NS5HNpGoRGzdK8HYxUtd65w9nBTA4dZ0MiRd3Wre5xjZp4XTz7w0P6X5sAqsXt73ynKSdARKSDbKDx3r5esHAE3a0bjnUR7Nmq4aques2SKdKNZf9pFFeeghAL8hdDPYWgfVIE1AJQLTopmRD2VUwKwrWetuSblU5DYydr7k0y3HNxDAehvD+DC227TluivL/JEHwduMkbhDX7v6UhOE03dUbI61yyaF1qhHHaJ3OHVE=
install:
- pip install tox
script: tox -e $TESTENV
branches:
  except:
  - /^\d/
notifications:
  email:
  - opensource-tests@paylogic.com
  slack:
    secure: Uwc6hfjc6ce6Ti6GmbDHW6Y7FUKAQzLpQD1BfaS+ZjnxngggmvZmh6p8aTFae7xFwGYHk9bYBOpInoyvxcvgLQjIRPIZ8NyNVOBP2kNcvUVEO42RCDMyEFN1V3buHW57sCA5ANwQYNyxmRf6S2BlIMpj4kR4eajzWM+y2MqfFHLi4ZH+Co0fiSnM1FfDnHKDt+K6Gpfl4vemlX35V0Uijavgafb2l2arWc2nc4tXT0bKcIEcW7r9cNEbOR9mFIV/PLiTpmfifwd6hsphw6nEOKD0tEk9TQkbATda7lazZWPHhEjViXFmfR5fa+vGBmCPvPG3s3H/2G/QqZQR/X5kyaTrchTQdPUXRB04nybmBkbieQHEq/EsFytDGYtK/piY2ErEzVBSv0BWmvda005XE5tDdvewfeihoZedG4rPMPtTfVRXFCj2SMG3eeaQ2RHkG2wkV8STSwMR51St3rkbv+1G9o7CxAEEZQDFqMjW/RUMySxm9sXoiD20A9jYTl4rh+oGUbWPJebxRPCly2b1fJnjxV1qmuKkK8Ll/KesWEQH7OriTi9cKJNxlkdnMd9QhbFj0LiHtjE+UHKub8x1mFoqyqkQ2K9oWY1p/fbpbKiR0UQ6yErczfTuUMZnLLi0Nf7hEFBE2wzIs32OAheAodLyV2E6MwaXoppSsn12z8A=
